update_entity_state:
  name: Atualizar Estado da Entidade
  description: Habilita ou desabilita uma entidade específica
  fields:
    entity_id:
      name: ID da Entidade
      description: ID da entidade a ser atualizada
      required: true
      selector:
        entity:
    enabled:
      name: Habilitado
      description: Se a entidade deve estar habilitada ou não
      required: true
      selector:
        boolean:

update_recorder_days:
  name: Atualizar Dias do Recorder
  description: Define quantos dias o histórico da entidade deve ser mantido
  fields:
    entity_id:
      name: ID da Entidade
      description: ID da entidade a ser atualizada
      required: true
      selector:
        entity:
    recorder_days:
      name: Dias no Recorder
      description: Número de dias para manter o histórico (0 = não gravar)
      required: true
      selector:
        number:
          min: 0
          max: 365
          step: 1

bulk_update:
  name: Atualização em Lote
  description: Atualiza múltiplas entidades de uma vez
  fields:
    entity_ids:
      name: IDs das Entidades
      description: Lista de entidades a serem atualizadas
      required: true
      selector:
        entity:
          multiple: true
    enabled:
      name: Habilitado
      description: Se as entidades devem estar habilitadas ou não (opcional)
      required: false
      selector:
        boolean:
    recorder_days:
      name: Dias no Recorder
      description: Número de dias para manter o histórico (opcional)
      required: false
      selector:
        number:
          min: 0
          max: 365
          step: 1

delete_entity:
  name: Excluir Entidade
  description: Remove permanentemente uma entidade do Home Assistant
  fields:
    entity_id:
      name: ID da Entidade
      description: ID da entidade a ser excluída
      required: true
      selector:
        entity:

bulk_delete:
  name: Excluir Entidades em Lote
  description: Remove permanentemente múltiplas entidades do Home Assistant
  fields:
    entity_ids:
      name: IDs das Entidades
      description: Lista de entidades a serem excluídas
      required: true
      selector:
        entity:
          multiple: true

purge_recorder:
  name: Limpar Recorder
  description: Remove dados antigos do recorder baseado nas configurações
  fields:
    entity_ids:
      name: IDs das Entidades
      description: Lista de entidades para limpar (vazio = todas configuradas)
      required: false
      selector:
        entity:
          multiple: true
    force_purge:
      name: Forçar Limpeza
      description: Força a limpeza mesmo para entidades com recorder_days=0
      required: false
      default: false
      selector:
        boolean:

intelligent_purge:
  name: Limpeza Inteligente do Recorder
  description: Executa limpeza automática baseada nas configurações de cada entidade
  fields:
    force_purge:
      name: Forçar Limpeza
      description: Força a limpeza mesmo para entidades com recorder_days=0
      required: false
      default: false
      selector:
        boolean:

generate_recorder_report:
  name: Gerar Relatório do Recorder
  description: Gera relatório das entidades com mais registros no banco de dados
  fields:
    limit:
      name: Limite de Entidades
      description: Número máximo de entidades no relatório
      required: false
      default: 100
      selector:
        number:
          min: 1
          max: 1000
          step: 1
    days_back:
      name: Período (Dias)
      description: Número de dias para analisar no histórico
      required: false
      default: 30
      selector:
        number:
          min: 1
          max: 365
          step: 1

# EXISTING SERVICES

update_recorder_exclude:
  name: Atualizar Exclusão do Recorder
  description: Marca ou desmarca uma entidade para exclusão do recorder
  fields:
    entity_id:
      name: ID da Entidade
      description: ID da entidade a ser atualizada
      required: true
      selector:
        entity:
    recorder_exclude:
      name: Excluir do Recorder
      description: Se a entidade deve ser excluída do recorder
      required: true
      selector:
        boolean:

bulk_update_recorder_exclude:
  name: Atualização em Lote - Exclusão do Recorder
  description: Marca ou desmarca múltiplas entidades para exclusão do recorder
  fields:
    entity_ids:
      name: IDs das Entidades
      description: Lista de entidades a serem atualizadas
      required: true
      selector:
        entity:
          multiple: true
    recorder_exclude:
      name: Excluir do Recorder
      description: Se as entidades devem ser excluídas do recorder
      required: true
      selector:
        boolean:

update_recorder_config:
  name: Atualizar Configuração do Recorder
  description: Cria/atualiza o arquivo recorder.yaml com configuração completa de domínios e entidades
  fields:
    backup_config:
      name: Fazer Backup
      description: Criar backup dos arquivos antes de atualizar
      required: false
      default: true
      selector:
        boolean:

purge_all_entities:
  name: Limpar Todas as Entidades
  description: Executa recorder.purge_entities para entidades marcadas para exclusão
  fields:
    force_purge:
      name: Forçar Limpeza
      description: Força a limpeza mesmo sem entidades marcadas
      required: false
      default: false
      selector:
        boolean:

# UPDATED DOMAIN SERVICES

exclude_domain:
  name: Excluir Domínio do Recorder
  description: Configura um domínio completo para exclusão do recorder com opção de definir dias de retenção
  fields:
    domain:
      name: Domínio
      description: Nome do domínio a ser configurado (ex. sensor, light, automation, etc.)
      required: true
      selector:
        select:
          options:
            - sensor
            - binary_sensor
            - light
            - switch
            - automation
            - script
            - scene
            - device_tracker
            - media_player
            - climate
            - cover
            - fan
            - lock
            - camera
            - vacuum
            - input_boolean
            - input_number
            - input_select
            - input_text
            - input_datetime
            - timer
            - counter
            - group
            - zone
            - person
            - sun
            - weather
            - calendar
            - notify
            - tts
            - alert
            - plant
          custom_value: true
    recorder_exclude:
      name: Excluir do Recorder
      description: Se o domínio deve ser completamente excluído do recorder
      required: false
      default: true
      selector:
        boolean:
    recorder_days:
      name: Dias de Retenção
      description: Número de dias para manter o histórico do domínio (apenas se não excluído)
      required: false
      selector:
        number:
          min: 1
          max: 730
          step: 1

include_domain:
  name: Incluir Domínio no Recorder
  description: Configura um domínio para inclusão no recorder com opção de definir dias de retenção
  fields:
    domain:
      name: Domínio
      description: Nome do domínio a ser incluído (ex. sensor, light, etc.)
      required: true
      selector:
        select:
          options:
            - sensor
            - binary_sensor
            - light
            - switch
            - automation
            - script
            - scene
            - device_tracker
            - media_player
            - climate
            - cover
            - fan
            - lock
            - camera
            - vacuum
            - input_boolean
            - input_number
            - input_select
            - input_text
            - input_datetime
            - timer
            - counter
            - group
            - zone
            - person
            - sun
            - weather
            - calendar
            - notify
            - tts
            - alert
            - plant
          custom_value: true
    recorder_days:
      name: Dias de Retenção
      description: Número de dias para manter o histórico do domínio (opcional)
      required: false
      selector:
        number:
          min: 1
          max: 730
          step: 1

bulk_exclude_domains:
  name: Configurar Múltiplos Domínios
  description: Configura múltiplos domínios para exclusão/inclusão no recorder com opção de definir dias de retenção
  fields:
    domains:
      name: Domínios
      description: Lista de domínios a serem configurados
      required: true
      selector:
        select:
          multiple: true
          custom_value: true
          options:
            - sensor
            - binary_sensor
            - light
            - switch
            - automation
            - script
            - scene
            - device_tracker
            - media_player
            - climate
            - cover
            - fan
            - lock
            - camera
            - vacuum
            - input_boolean
            - input_number
            - input_select
            - input_text
            - input_datetime
            - timer
            - counter
            - group
            - zone
            - person
            - sun
            - weather
            - calendar
            - notify
            - tts
            - alert
            - plant
    recorder_exclude:
      name: Excluir do Recorder
      description: Se os domínios devem ser excluídos do recorder
      required: false
      default: true
      selector:
        boolean:
    recorder_days:
      name: Dias de Retenção
      description: Número de dias para manter o histórico dos domínios (apenas se não excluídos)
      required: false
      selector:
        number:
          min: 1
          max: 730
          step: 1

# NEW DOMAIN RECORDER DAYS SERVICES

update_domain_recorder_days:
  name: Atualizar Dias de Retenção do Domínio
  description: Define o número de dias de retenção para um domínio específico
  fields:
    domain:
      name: Domínio
      description: Nome do domínio a ser configurado
      required: true
      selector:
        select:
          options:
            - sensor
            - binary_sensor
            - light
            - switch
            - automation
            - script
            - scene
            - device_tracker
            - media_player
            - climate
            - cover
            - fan
            - lock
            - camera
            - vacuum
            - input_boolean
            - input_number
            - input_select
            - input_text
            - input_datetime
            - timer
            - counter
            - group
            - zone
            - person
            - sun
            - weather
            - calendar
            - notify
            - tts
            - alert
            - plant
          custom_value: true
    domain_recorder_days:
      name: Dias de Retenção do Domínio
      description: Número de dias para manter o histórico de todas as entidades do domínio
      required: true
      selector:
        number:
          min: 1
          max: 730
          step: 1

bulk_update_domain_recorder_days:
  name: Atualizar Dias de Retenção - Múltiplos Domínios
  description: Define o número de dias de retenção para múltiplos domínios
  fields:
    domains:
      name: Domínios
      description: Lista de domínios a serem configurados
      required: true
      selector:
        select:
          multiple: true
          custom_value: true
          options:
            - sensor
            - binary_sensor
            - light
            - switch
            - automation
            - script
            - scene
            - device_tracker
            - media_player
            - climate
            - cover
            - fan
            - lock
            - camera
            - vacuum
            - input_boolean
            - input_number
            - input_select
            - input_text
            - input_datetime
            - timer
            - counter
            - group
            - zone
            - person
            - sun
            - weather
            - calendar
            - notify
            - tts
            - alert
            - plant
    domain_recorder_days:
      name: Dias de Retenção do Domínio
      description: Número de dias para manter o histórico de todas as entidades dos domínios selecionados
      required: true
      selector:
        number:
          min: 1
          max: 730
          step: 1

reload_config:
  name: Recarregar Configuração
  description: Recarrega as configurações do Entity Manager dos arquivos