update_entity_state:
  name: Atualizar Estado da Entidade
  description: Habilita ou desabilita uma entidade específica
  fields:
    entity_id:
      name: ID da Entidade
      description: ID da entidade a ser atualizada
      required: true
      selector:
        entity:
    enabled:
      name: Habilitado
      description: Se a entidade deve estar habilitada ou não
      required: true
      selector:
        boolean:

update_recorder_days:
  name: Atualizar Dias do Recorder
  description: Define quantos dias o histórico da entidade deve ser mantido
  fields:
    entity_id:
      name: ID da Entidade
      description: ID da entidade a ser atualizada
      required: true
      selector:
        entity:
    recorder_days:
      name: Dias no Recorder
      description: Número de dias para manter o histórico (0 = não gravar)
      required: true
      selector:
        number:
          min: 0
          max: 365
          step: 1

bulk_update:
  name: Atualização em Lote
  description: Atualiza múltiplas entidades de uma vez
  fields:
    entity_ids:
      name: IDs das Entidades
      description: Lista de entidades a serem atualizadas
      required: true
      selector:
        entity:
          multiple: true
    enabled:
      name: Habilitado
      description: Se as entidades devem estar habilitadas ou não (opcional)
      required: false
      selector:
        boolean:
    recorder_days:
      name: Dias no Recorder
      description: Número de dias para manter o histórico (opcional)
      required: false
      selector:
        number:
          min: 0
          max: 365
          step: 1

delete_entity:
  name: Excluir Entidade
  description: Remove permanentemente uma entidade do Home Assistant
  fields:
    entity_id:
      name: ID da Entidade
      description: ID da entidade a ser excluída
      required: true
      selector:
        entity:

bulk_delete:
  name: Excluir Entidades em Lote
  description: Remove permanentemente múltiplas entidades do Home Assistant
  fields:
    entity_ids:
      name: IDs das Entidades
      description: Lista de entidades a serem excluídas
      required: true
      selector:
        entity:
          multiple: true

purge_recorder:
  name: Limpar Recorder
  description: Remove dados antigos do recorder baseado nas configurações
  fields:
    entity_ids:
      name: IDs das Entidades
      description: Lista de entidades para limpar (vazio = todas configuradas)
      required: false
      selector:
        entity:
          multiple: true
    force_purge:
      name: Forçar Limpeza
      description: Força a limpeza mesmo para entidades com recorder_days=0
      required: false
      default: false
      selector:
        boolean:

intelligent_purge:
  name: Limpeza Inteligente do Recorder
  description: Executa limpeza automática baseada nas configurações de cada entidade
  fields:
    force_purge:
      name: Forçar Limpeza
      description: Força a limpeza mesmo para entidades com recorder_days=0
      required: false
      default: false
      selector:
        boolean:

generate_recorder_report:
  name: Gerar Relatório do Recorder
  description: Gera relatório das entidades com mais registros no banco de dados
  fields:
    limit:
      name: Limite de Entidades
      description: Número máximo de entidades no relatório
      required: false
      default: 100
      selector:
        number:
          min: 1
          max: 1000
          step: 1
    days_back:
      name: Período (Dias)
      description: Número de dias para analisar no histórico
      required: false
      default: 30
      selector:
        number:
          min: 1
          max: 365
          step: 1

# NOVOS SERVIÇOS

update_recorder_exclude:
  name: Atualizar Exclusão do Recorder
  description: Marca ou desmarca uma entidade para exclusão do recorder
  fields:
    entity_id:
      name: ID da Entidade
      description: ID da entidade a ser atualizada
      required: true
      selector:
        entity:
    recorder_exclude:
      name: Excluir do Recorder
      description: Se a entidade deve ser excluída do recorder
      required: true
      selector:
        boolean:

bulk_update_recorder_exclude:
  name: Atualização em Lote - Exclusão do Recorder
  description: Marca ou desmarca múltiplas entidades para exclusão do recorder
  fields:
    entity_ids:
      name: IDs das Entidades
      description: Lista de entidades a serem atualizadas
      required: true
      selector:
        entity:
          multiple: true
    recorder_exclude:
      name: Excluir do Recorder
      description: Se as entidades devem ser excluídas do recorder
      required: true
      selector:
        boolean:

update_recorder_config:
  name: Atualizar Configuração do Recorder
  description: Atualiza o configuration.yaml com entidades excluídas do recorder
  fields:
    backup_config:
      name: Fazer Backup
      description: Criar backup do configuration.yaml antes de atualizar
      required: false
      default: true
      selector:
        boolean:

purge_all_entities:
  name: Limpar Todas as Entidades
  description: Executa recorder.purge_entities para entidades marcadas para exclusão
  fields:
    force_purge:
      name: Forçar Limpeza
      description: Força a limpeza mesmo sem entidades marcadas
      required: false
      default: false
      selector:
        boolean:

reload_config:
  name: Recarregar Configuração
  description: Recarrega a configuração do arquivo